INSERT INTO curso (nomeCurso) VALUES ("Técnico Agrícola");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Informática para Internet Integrado ao Ensino Médio");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Informática Integrado ao Ensino Médio");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Meio Ambiente Integrado ao Ensino Médio");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Agropecuária Integrado ao Ensino Médio");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Administração");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Informática");
INSERT INTO curso (nomeCurso) VALUES ("Bacharelado em Sistemas de Informação");
INSERT INTO curso (nomeCurso) VALUES ("Bacharelado em Zootecnia");
INSERT INTO curso (nomeCurso) VALUES ("Bacharelado em Agronomia");
INSERT INTO curso (nomeCurso) VALUES ("Licenciatura em Ciências Biológicas");
INSERT INTO curso (nomeCurso) VALUES ("Licenciatura em Química");
INSERT INTO curso (nomeCurso) VALUES ("Especialização em Ensino de Ciências da Natureza e Educação Matemática");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Agroindústria - PROEJA");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Administração - PROEJA");
INSERT INTO curso (nomeCurso) VALUES ("Técnico em Manutenção e Suporte em Informática - PROEJA");
INSERT INTO curso (nomeCurso) VALUES ("Mestrado em Irrigação do Cerrado");
INSERT INTO curso (nomeCurso) VALUES ("Mulheres Mil / FIC");
INSERT INTO curso (nomeCurso) VALUES ("Certific");
INSERT INTO curso (nomeCurso) VALUES ("EAD");