-- MySQL Script generated by MySQL Workbench
-- 08/13/18 11:35:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `NomePais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(50) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`, `idPais`),
  INDEX `fk_estado_pais1_idx` (`idPais` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(100) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`, `idEstado`),
  INDEX `fk_cidade_estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `mydb`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`egresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`egresso` (
  `idEgresso` INT NOT NULL AUTO_INCREMENT,
  `nomeEgresso` VARCHAR(100) NOT NULL,
  `cpfEgresso` INT NOT NULL,
  `dataNascimentoEgresso` DATE NOT NULL,
  `emailEgresso` VARCHAR(80) NOT NULL,
  `telefoneEgresso` INT NOT NULL,
  `sexoEgresso` VARCHAR(2) NOT NULL,
  `whatsappEgresso` INT NULL,
  `enderecoEgresso` VARCHAR(100) NOT NULL,
  `numeroEnderecoEgresso` INT(10) NOT NULL,
  `setorEnderecoEgresso` VARCHAR(50) NOT NULL,
  `complementoEgresso` VARCHAR(100) NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`idEgresso`, `idCidade`),
  INDEX `fk_egresso_cidade1_idx` (`idCidade` ASC),
  CONSTRAINT `fk_egresso_cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `mydb`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursoConcluido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursoConcluido` (
  `idCursoConcluido` INT NOT NULL,
  `anoFimCursoConcluido` INT NOT NULL,
  `anoInicioCursoConcluido` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idEgresso` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idEgresso`),
  INDEX `fk_curso_has_egresso_egresso1_idx` (`idEgresso` ASC),
  INDEX `fk_curso_has_egresso_curso_idx` (`idCurso` ASC),
  CONSTRAINT `fk_curso_has_egresso_curso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_egresso_egresso1`
    FOREIGN KEY (`idEgresso`)
    REFERENCES `mydb`.`egresso` (`idEgresso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pergunta` (
  `idPergunta` INT NOT NULL AUTO_INCREMENT,
  `enunciadoPergunta` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idPergunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resposta` (
  `idResposta` INT NOT NULL,
  `resultadoResposta` SMALLINT(2) NOT NULL,
  `idEgresso` INT NOT NULL,
  `idPergunta` INT NOT NULL,
  PRIMARY KEY (`idResposta`, `idEgresso`, `idPergunta`),
  INDEX `fk_resposta_egresso1_idx` (`idEgresso` ASC),
  INDEX `fk_resposta_pergunta1_idx` (`idPergunta` ASC),
  CONSTRAINT `fk_resposta_egresso1`
    FOREIGN KEY (`idEgresso`)
    REFERENCES `mydb`.`egresso` (`idEgresso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_pergunta1`
    FOREIGN KEY (`idPergunta`)
    REFERENCES `mydb`.`pergunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
